# -*- coding: utf-8 -*-
"""Task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yhDhDSjwjBeHYm29V_poXipaNJBbvh1
"""

#Data_understanding
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    "Order_ID": ["ORD001","ORD002","ORD003","ORD004","ORD005","ORD006","ORD007","ORD008","ORD009","ORD010",
                 "ORD011","ORD012","ORD013","ORD014","ORD015","ORD016","ORD017","ORD018","ORD019","ORD020"],

    "Product_Category": ["Electronics","Clothing","Groceries","Electronics","Furniture",
                         "Clothing","Electronics","Groceries","Furniture","Clothing",
                         "Electronics","Furniture","Groceries","Clothing","Electronics",
                         "Furniture","Groceries","Electronics","Clothing","Furniture"],

    "Customer_Age": [25,32,28,41,35,24,29,45,38,27,31,42,26,36,30,48,33,29,40,37],

    "Quantity": [2,4,6,1,3,5,2,8,2,4,3,1,7,5,2,2,9,3,4,2],

    "Unit_Price": [500,800,120,1500,2200,650,1800,100,2500,750,
                   1200,3000,150,900,2000,2800,130,1600,850,2400],

    "Discount": [5,10,0,15,8,5,10,0,12,5,8,15,0,10,5,12,10,0,8,5],

    "Delivery_Days": [3,5,2,4,7,3,4,2,8,5,3,6,2,4,3,7,2,4,5,6],

    "Sales": [950,2880,720,1275,6072,3087,3240,800,4400,2850,
              3312,2550,1050,4050,3520,5040,1170,4416,3230,4560]
}

df=pd.DataFrame(data)
df

df.head()

df.tail()

df.shape

df.dtypes

df.info()

#Data_cleaning
df.isnull().sum()

df.duplicated().sum()

print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

#statistics
df['Sales'].mean()

df['Sales'].median()

df['Sales'].min()

df['Sales'].max()

df["Sales"].max() - df["Sales"].min()

df["Sales"].std()

df['Quantity'].mean()

df['Delivery_Days'].mean()

#Data Visualization
plt.hist(df["Sales"],bins=8)
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.title("Distribution of Sales")
plt.show()# used to visualize how sales values are distributed

plt.boxplot(df["Sales"])
plt.ylabel("Sales")
plt.title("Box plot of sales")
plt.show()

category_sales = df.groupby("Product_Category")["Sales"].sum()
category_sales

category_sales.plot(kind="bar")

plt.xlabel("Product Category")
plt.ylabel("Total Sales")
plt.title("Sales by Product Category")
plt.xticks(rotation=0)
plt.show()

category_sales.idxmax()

plt.scatter(df["Quantity"],df["Sales"])
plt.xlabel("Quanity")
plt.ylabel("Sales")
plt.title("Quanity vs Sales")
plt.show()

plt.scatter(df["Unit_Price"], df["Sales"])
plt.xlabel("Unit Price")
plt.ylabel("Sales")
plt.title("Unit Price vs Sales")
plt.show()

plt.scatter(df["Delivery_Days"], df["Sales"])
plt.xlabel("Delivery Days")
plt.ylabel("Sales")
plt.title("Delivery Days vs Sales")
plt.show()

#correlation
correlation = df[
    ["Quantity", "Unit_Price", "Discount", "Delivery_Days", "Sales"]
].corr()

correlation

sales_correlation = correlation["Sales"].drop("Sales")
print(sales_correlation)

strongest_variable = sales_correlation.abs().idxmax()

print("Strongest relationship with Sales:", strongest_variable)

from sklearn.linear_model import LinearRegression

X = df[
    ["Customer_Age", "Quantity", "Unit_Price", "Discount", "Delivery_Days"]
]

y = df["Sales"] # predict

model = LinearRegression()
model.fit(X, y)

new_order = pd.DataFrame({
    "Customer_Age": [30],
    "Quantity": [4],
    "Unit_Price": [1000],
    "Discount": [5],
    "Delivery_Days": [3]
})

predicted_sales = model.predict(new_order)
print("Predicted Sales:", predicted_sales[0])